const menu = [
    {
        id : 1,
        title : 'buttermilk pancakes',
        category : 'breakfast',
        price : 15.99,
        img : './images/item-1.jpeg',
        desc : `I am baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed`,
    },
    {
        id : 2,
        title : 'diner double',
        category : 'lunch',
        price : 13.99,
        img : './images/item-2.jpeg',
        desc : `Lorem ipsum, dolor sit amet consectetur adipisicing elit. Placeat, nemo.`,
    },
    {
        id : 3,
        title : 'godzilla milkshake',
        category : 'shakes',
        price : 6.99,
        img : './images/item-3.jpeg',
        desc : `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae nihil vitae, neque maiores dolorem voluptatem?`,
    },
    {
        id : 4,
        title : 'country delight',
        category : 'breakfast',
        price : 20.99,
        img : './images/item-1.jpeg',
        desc : `Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde reiciendis quis voluptas tempora.`,
    },
    {
        id : 5,
        title : 'buttermilk pancakes',
        category : 'breakfast',
        price : 15.99,
        img : './images/item-1.jpeg',
        desc : `I am baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed`,
    },
    {
        id : 6,
        title : 'buttermilk pancakes',
        category : 'breakfast',
        price : 15.99,
        img : './images/item-1.jpeg',
        desc : `I am baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed`,
    },
    {
        id : 7,
        title : 'buttermilk pancakes',
        category : 'breakfast',
        price : 15.99,
        img : './images/item-1.jpeg',
        desc : `I am baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed`,
    },
    {
        id : 8,
        title : 'buttermilk pancakes',
        category : 'breakfast',
        price : 15.99,
        img : './images/item-1.jpeg',
        desc : `I am baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed`,
    },
    {
        id : 9,
        title : 'buttermilk pancakes',
        category : 'breakfast',
        price : 15.99,
        img : './images/item-1.jpeg',
        desc : `I am baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed`,
    }
    
]